name: Django CI with Docker

on:
  push:
    branches: [ "pruebas" ]
  pull_request:
    branches: [ "pruebas" ]
 
jobs:
  build:
    runs-on: self-hosted
    env:
      PYTHONDONTWRITEBYTECODE: 1

    steps:
      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Corregir permisos antes del checkout
        run: |
          sudo chown -R $(whoami) /home/vboxuser/django_tests
          sudo chmod -R 777 /home/vboxuser/django_tests

      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar docker-compose v2
        run: |
          sudo apt-get remove -y docker-compose
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version


      - name: Remove old docker-compose
        run: |
         # 1. Elimina cualquier rastro previo de docker-compose (no causa error si no existe)
          sudo apt-get remove -y docker-compose || true
          sudo rm -f /usr/local/bin/docker-compose

          # 2. Descarga Docker Compose usando tee para que la redirección se ejecute con privilegios de root
          sudo sh -c 'curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" | tee /usr/local/bin/docker-compose > /dev/null'

          # 3. Asigna permisos de ejecución al binario descargado
          sudo chmod +x /usr/local/bin/docker-compose

          # 4. Verifica la instalación
          docker-compose --version




      - name: Ejecutar tests de Django dentro del contenedor
        run: |
          sleep 5
          docker exec django-app python manage.py test

      - name: Ejecutar tests con cobertura dentro del contenedor
        run: |
          docker exec django-app coverage run --include="myapp/models.py,myapp/views.py" manage.py test

      - name: Generar reporte de cobertura en HTML dentro del contenedor
        run: |
          docker exec django-app coverage html

      - name: Subir reporte de cobertura como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
      - name: Reporte de cobertura y verificación del mínimo requerido
        run: |
          docker exec django-app coverage report
          docker exec django-app coverage report --fail-under=62

      - name: Limpiar directorio htmlcov para evitar problemas de permisos
        run: |
          sudo rm -rf htmlcov
