name: Django CI with Docker

on:
  push:
    branches: [ "pruebas" ]
  pull_request:
    branches: [ "pruebas" ]

jobs:
  build:
    runs-on: self-hosted
    env:
      PYTHONDONTWRITEBYTECODE: 1

    steps:
      - name: Corregir permisos antes del checkout
        run: |
          sudo chown -R $(whoami) ${{ github.workspace }}
          sudo chmod -R 777 ${{ github.workspace }}

      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Construir imagen de Docker para tests
        run: docker build -t django-test .

      - name: Ejecutar tests de Django con cobertura
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            django-test \
            sh -c "coverage run --source=. manage.py test && coverage html"

      - name: Subir reporte de cobertura como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      - name: Reporte de cobertura y verificación del mínimo requerido
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            django-test \
            sh -c "coverage report --fail-under=62"

      - name: Limpiar directorio htmlcov para evitar problemas de permisos
        run: rm -rf htmlcov
